Update cost to const
kentcdodds/es6-workshop pull request #11
Opened 2016-09-15 20:24 UTC by hollyglot

2016-09-15 22:25 UTC, kentcdodds commented on exercises/01_block-scoping.test.js
> +  // once you've changed the `var` above to `const`, comment out the line below
Wonderful! Thanks for letting me know! If you'd like, could you make this change in `templates/`? The `exercises` directory is generated :)

2016-09-15 22:25 UTC, kentcdodds requested changes

2016-09-16 12:07 UTC, gudmundurmar commented
Ah, was just about to open this too. Fixing this ASAP would be drowning in PRs :)
Just a quick question though @kentcdodds. How are you generating the exercises through templates and why?

2016-09-16 12:11 UTC, kentcdodds commented
I wrote a tool called [`split-guide`](http://git.io/split-guide) to generate it because it makes it easier to keep the exercieses and exercieses-final directories in sync :) It's actually pretty brilliant :)

2016-12-22 04:29 UTC, kentcdodds commented
I'll go ahead and make this change myself. Thanks!

2016-12-22 04:29 UTC, closed without merging