Quiz 10 on class syntax
kentcdodds/es6-workshop pull request #28
Opened 2017-01-08 07:08 UTC by alayek

There is one pattern not covered in the tests in templates. It's when you extend a class and you **have** to override a function - similar to abstract class / interface in Java-type languages.

I noticed this pattern in the source code of octotree - In [this line](https://github.com/buunguyen/octotree/blob/master/src/adapters/adapter.js#L226) and [this line](https://github.com/buunguyen/octotree/blob/master/src/adapters/adapter.js#L286). 

This is why the classes that extend them, have to implement these methods (like [here](https://github.com/buunguyen/octotree/blob/master/src/adapters/github.js#L106) and [here](https://github.com/buunguyen/octotree/blob/master/src/adapters/github.js#L216)) or face a runtime error.

Do you want to include an example on that?

2017-01-09 03:52 UTC, kentcdodds requested changes
Looks pretty good. Just a couple of things to move things around.

> you extend a class and you have to override a function - similar to abstract class / interface in Java-type languages.

Unless I'm misunderstanding you, I don't believe that's true. [See this example](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&code=class%20Parent%20%7B%0A%20%20sayHi()%20%7B%0A%20%20%20%20return%20'hey'%0A%20%20%7D%0A%7D%0A%0Aclass%20Child%20extends%20Parent%20%7B%0A%7D%0A%0Aconst%20child%20%3D%20new%20Child()%0Aconsole.log(child.sayHi()))

2017-01-09 03:52 UTC, kentcdodds commented on quizzes/10_class.test.js
> +const w = Voxel.fromObj({x: 2, y: 3.4, z: 7.9});
Let's move these to the top and keep everything in a single `console.log`.

2017-01-09 03:52 UTC, kentcdodds commented on quizzes/10_class.test.js
> +function Pixel(x=0, y=0) {
I think we'll need to move the `console.log` to the bottom because the `class` wont get hoisted like a function declaration does.

2017-01-10 15:10 UTC, alayek commented
> Unless I'm misunderstanding you, I don't believe that's true. See this example

No, I mean, as a library author; how do I enforce that if someone is extending my classes, they **have** to implement / override some of the methods?

2017-01-10 15:30 UTC, kentcdodds commented
Oh, I see. Perhaps that could be an extra credit test, but I don't think it's necessary in the quiz. Thanks!

2017-01-11 04:43 UTC, merged